services:
  - type: web
    name: car-valuation-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8001
      - key: ALLOWED_ORIGINS
        value: https://carmarket-six.vercel.app
    healthCheckPath: /health
    plan: free  # hoặc starter/standard nếu muốn upgrade

